### ISSUE TITLE
Malwarebytes Flagging as Malware.AI.2262024049

### ISSUE THREAD

**Issue by jackfruh** [AderitoSilva/XInputium#1]
This looks like the perfect input library for my C# .net 6 project!

Unfortunately, when I run the sample project, it gets flagged by malwarebytes.
(the specific file quarantined  is XInputium.Preview.dll)

Have you run into this?

I can spend some time to review all the code to make sure it's not malicious, but my concern is that my application, once it incorporates this, will also get flagged and won't be usable by my users.

Thoughts?

**Comment by AderitoSilva** [comment]
Those are outdated false positives that, according to VirusTotal, affected Malwarebytes and Bkav Pro. I reanalyzed the latest version files on VirusTotal and all results come now clean by all antivirus products. Before the reanalysis of `XInputium.Preview.dll`, it was indeed reported by Malwarebytes and Bkav Pro, which, from the name of the detection, seemed to have been detected by some automatic/AI based heuristic for some reason. 

## VirusTotal results
I ran a reanalysis on VirusTotal and all files are now reported as clean by all antiviruses. Those false positives seem to have now been updated. The analyzed files are the ones from version 1.2.0 that I reanalyzed:
 - **XInputium.Preview.exe**: [https://www.virustotal.com/gui/file/e0ab4fb20bc77031b0c94f4d2f2e617a6573c4a746d0cbb5cdcdf4da8f793318?nocache=1](https://www.virustotal.com/gui/file/e0ab4fb20bc77031b0c94f4d2f2e617a6573c4a746d0cbb5cdcdf4da8f793318?nocache=1)
  - **XInputium.Preview.dll**: [https://www.virustotal.com/gui/file/5b8b75eaf37542dcdc9489f017933465ce6724d88daca9c866bdec728db0b9b1?nocache=1](https://www.virustotal.com/gui/file/5b8b75eaf37542dcdc9489f017933465ce6724d88daca9c866bdec728db0b9b1?nocache=1)
  - **XInputium.dll**: [https://www.virustotal.com/gui/file/a487ba91cbd8cbcd126c93bc78c872b95bd599d8acb56aada2648fc52257f05b?nocache=1](https://www.virustotal.com/gui/file/a487ba91cbd8cbcd126c93bc78c872b95bd599d8acb56aada2648fc52257f05b?nocache=1)

You may notice that the file `XInputium.Preview.exe` appears on VirusTotal with the name `XInputium.Preview.dll`, but you can look at the file size to check that it is actually the one from `XInputium.Preview.exe`. I recommend you run your own analysis on the files you have on VirusTotal.

Even though VirusTotal shows no detection, could you confirm if the Malwarebytes software you're using is still detecting an XInputium file as virus? Maybe you would have to update your Malwarebytes first, I believe. If it still detects, I will submit the affected file(s) to Malwarebytes to report them as a false-positives.
